### ISSUE TITLE
连接断开的时候没有重新监听事件

### ISSUE THREAD

**Issue by wenfer** [zhouhailin/freeswitch-esl-all#32]
freeswitch不知道为啥，大概一天会断开一次连接，重新连上的时候之前监听的事件就收不到了。
我试过用ServerConnectionListener在连接连上的时候去监听，但好像这个事件发生的时候，client还没有初始化，调用监听事件会报没有权限，所以我现在是加了异步延时去弄，这个问题有其他好的办法解决吗

**Comment by zhouhailin** [comment]
这个需要看下日志，按照当前设计会自动重新连接上并订阅相应的事件

**Comment by wenfer** [comment]
> 这个需要看下日志，按照当前设计会自动重新连接上并订阅相应的事件

我的版本是1.6.7.RELEASE，目前看下来没有自动重新订阅

**Comment by VIHATTeam** [comment]
i have same situation, any suggest @zhouhailin

**Comment by wenfer** [comment]
```
<!--StartFragment-->

2023-10-31 09:15:16 |  
-- | --
  |   | 2023-10-31 09:15:16 | at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
  |   | 2023-10-31 09:15:16 | at ServerConnectionListenerImpl.lambda$onOpened$0(ServerConnectionListenerImpl.java:34) ~[call-manager-1.0-SNAPSHOT.jar!/:1.0-SNAPSHOT]
  |   | 2023-10-31 09:15:16 | at com.sun.proxy.$Proxy183.setEventSubscriptions(Unknown Source) ~[na:na]
  |   | 2023-10-31 09:15:16 | at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  |   | 2023-10-31 09:15:16 | at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
  |   | 2023-10-31 09:15:16 | at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
  |   | 2023-10-31 09:15:16 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
  |   | 2023-10-31 09:15:16 | at sun.reflect.GeneratedMethodAccessor715.invoke(Unknown Source) ~[na:na]
  |   | 2023-10-31 09:15:16 | at link.thingscloud.freeswitch.esl.inbound.NettyInboundClient.setEventSubscriptions(NettyInboundClient.java:135) ~[freeswitch-esl-1.6.7.RELEASE.jar!/:na]
  |   | 2023-10-31 09:15:16 | at link.thingscloud.freeswitch.esl.inbound.NettyInboundClient.getAuthedHandler(NettyInboundClient.java:41) ~[freeswitch-esl-1.6.7.RELEASE.jar!/:na]
  |   | 2023-10-31 09:15:16 | at link.thingscloud.freeswitch.esl.inbound.AbstractInboundClient.getAuthedHandler(AbstractInboundClient.java:261) ~[freeswitch-esl-1.6.7.RELEASE.jar!/:na]
  |   | 2023-10-31 09:15:16 | link.thingscloud.freeswitch.esl.exception.InboundClientException: inbound handler is not authed for addr : 192.168.3.3:8021

<!--EndFragment-->
```

**Comment by wenfer** [comment]
@zhouhailin 好像每隔一段时间就会出这个错，我在代码中重新订阅也订阅不上，就会报这个错
